debug: true
server:
  port: 8801
eureka:
  instance:
      ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://root:root@localhost:8800/eureka/

spring:
  application:
    name: zuul-service
zuul:
  routes:
    user:
      path: /user/**
      service-id: user-service
#      url : http://localhost:8802/
      stripPrefix: true

logging.level.org.springframework.boot.autoconfigure: ERROR