spring:
  application:
    name: user-service
  datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/demo?autoReconnect=false&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver